version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ptu-server
    ports:
      - '3000:3000'
      - '3001:3001'
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: ptu_learning
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - db
      - redis
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: pnpm start:dev

  db:
    image: postgres:15
    container_name: ptu-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ptu_learning
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: ptu-redis
    ports:
      - '6379:6379'

volumes:
  pgdata:
