export const JOB_NAME = {
  SEND_WELCOME_EMAIL: 'SEND_WELCOME_EMAIL',
  SEND_OTP_EMAIL: 'SEND_OTP_EMAIL',
  INDEX_SEARCH: 'INDEX_SEARCH',
  DELETE_INDEX: 'DELETE_INDEX',
  SAVE_MESSAGE: 'SAVE_MESSAGE',
} as const;
